### ISSUE TITLE
Starting a session from ReGreet doesn't seem to set env vars from `~/.config/environment.d/`

### ISSUE THREAD

**Issue by hkupty** [rharish101/ReGreet#59]
Due to a bug in wlgreet resulting in it being incompatible w/ sway 1.9, I changed to ReGreet.
Everything seems to work fine, except for my env vars defined in `~/.config/environment.d/`. Given this is the only change (except for, obviously, sway itself), I assume this is behind the change in behavior as it is responsible for how the session is started.

**Comment by rharish101** [comment]
Does this mean that when you start your session from ReGreet, your DE/WM/compositor doesn't source that file, whereas it did while running through wlgreet? Because ReGreet itself just does the following:
- Loads the command from the session file
- Loads the custom environment variables from the config file

Looking through the source code for wlgreet (https://git.sr.ht/~kennylevinsen/wlgreet/tree/master/item/src/widgets/login.rs#L125), it seems to do the same, except for loading env vars.

Could you post logs for ReGreet, and possibly for wlgreet? ReGreet shouldn't be able to read your home directory anyway, and thus it can't source `~/config/environment.d`. However, if your DE/WM/compositor fails to source it in this case, while working well through wlgreet, then something's up.

**Comment by hkupty** [comment]
I noted what was the issue and it has nothing to do with ReGreet. wlgreet was launching the sway session through a custom script. I'll close the issue, sorry for taking your time.
