### ISSUE TITLE
How can I change the xkb keyboard layout in greeter?

### ISSUE THREAD

**Issue by Yucklys** [rharish101/ReGreet#61]
I am a Dvorak user, but the default keyboard layout of regreet is set to QWERTY. Is there any way to change the xkb setting so I can use my favorite layout?

OS: NixOS unstable
ReGreet version: 0.1.1

**Comment by rharish101** [comment]
You'll have to edit the config file of the Wayland compositor that you use to launch ReGreet, like Sway or Hyprland. I'm not aware of a compositor-independent way of switching the keyboard layout on Wayland. If there is, please post a message on this issue, so that I can reopen it and turn it into a feature request.
