### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by haselwarter** [rharish101/ReGreet#82]
Hi, first off, thank you for the nice project!

I noticed that the latest release is over a year old, and that some of the features described in the current README are missing from that release (e.g., `--demo`). Could you cut a new release?

**Comment by rharish101** [comment]
I plan to release them as part of 0.2.0 once I've merged a couple of PRs that introduce non-breaking changes (namely #16 and #81). If you want, you could help accelerate them by testing those PRs 😛.

**Comment by JL2210** [comment]
I used those for a while and didn't see any issues with e.g. Plasma on X11

Maybe merge them and see if people complain? It took a bit of time for me to pull those in and rebuild, I doubt many other people would do the same.

**Comment by svenstaro** [comment]
@rharish101 could you maybe just cut a release? I think at these low version numbers people don't really expect it to be stable. You must merge #87 before, though, as otherwise this thing won't even launch.

**Comment by rharish101** [comment]
Done, sorry for the delay! As for the low version numbers, I don't think people should consider it to be a "stable" release, because:
* There's still a lot of feature requests that might lead to breaking changes.
* I'm still just a random dude maintaining it in his free time, so I can't guarantee the quality that people expect of "stable" software.
